"""
APEX FACTORY v6.0 - Factory Layer
File: mobile_factory.py

Mục đích: Target React Native (Expo) - sinh app di động từ DesignGraph.
    Khác ReactEmitter web ở 2 điểm cốt lõi:
      1. HTML tag → RN primitive: div→View, span→Text, button→Pressable, ...
      2. className → NativeWind (nativewind package cho phép dùng Tailwind trên RN)

Output:
    app/
    ├── index.ts                       entry
    ├── App.tsx                        root
    ├── components/<Name>/<Name>.tsx   per-component file
    ├── styles/tokens.css              NativeWind v4 dùng global.css
    ├── tailwind.config.js             NativeWind config
    ├── babel.config.js                BẮT BUỘC có nativewind preset
    ├── metro.config.js                NativeWind v4 require
    ├── app.json                       Expo config
    ├── package.json
    └── tsconfig.json
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from apex_core.emitters.ast_backbone import (
    TS_ANY,
    TS_BOOLEAN,
    TS_NUMBER,
    TS_REACT_NODE,
    TS_STRING,
    TS_UNKNOWN,
    CodeEmitter,
    FileModule,
    FunctionDeclaration,
    FunctionParam,
    ImportSpec,
    JSXAttribute,
    JSXNode,
    TSInterface,
    TSProperty,
    TSType,
    to_camel_case,
    to_jsx_value,
    to_pascal_case,
)
from apex_core.emitters.react_emitter import EmitResult
from apex_core.emitters.tailwind_stylist import (
    ClassList,
    TailwindConfigBuilder,
)
from apex_core.foundation.ontology_ui import (
    ComponentCatalog,
    ComponentSpec,
    PropSchema,
    RenderTarget,
    TokenRegistry,
)
from apex_core.foundation.principles_v6 import (
    PrincipleV6,
    enforce_principle_v6,
)
from apex_core.foundation.ui_ir import (
    DataSourceKind,
    DesignGraph,
    DesignNode,
)

# ============================================================
# 0. VERSION + CONSTANTS
# ============================================================

MOBILE_FACTORY_VERSION = "6.0.0"

EXPO_SDK_VERSION = "^51.0.0"
RN_VERSION = "0.74.5"
REACT_VERSION_RN = "18.2.0"
NATIVEWIND_VERSION = "^4.1.0"
REACT_NAVIGATION_VERSION = "^6.1.17"


# Map HTML tag → React Native component
HTML_TO_RN: Dict[str, str] = {
    "div":       "View",
    "span":      "Text",
    "section":   "View",
    "article":   "View",
    "aside":     "View",
    "header":    "View",
    "footer":    "View",
    "main":      "View",
    "nav":       "View",
    "h1":        "Text",
    "h2":        "Text",
    "h3":        "Text",
    "h4":        "Text",
    "h5":        "Text",
    "h6":        "Text",
    "p":         "Text",
    "a":         "Pressable",
    "button":    "Pressable",
    "img":       "Image",
    "ul":        "View",
    "ol":        "View",
    "li":        "View",
    "form":      "View",
    "input":     "TextInput",
    "textarea":  "TextInput",
    "label":     "Text",
    "table":     "View",
    "tr":        "View",
    "td":        "View",
    "th":        "View",
    "picture":   "View",
    "video":     "Video",        # expo-av
    "blockquote": "View",
}


# RN built-in components cần import từ 'react-native'
RN_BUILTIN_COMPONENTS: Set[str] = {
    "View", "Text", "Pressable", "Image", "TextInput", "ScrollView",
    "FlatList", "SafeAreaView", "StatusBar", "StyleSheet",
}


# ============================================================
# 1. MOBILE EMIT CONFIG
# ============================================================

@dataclass
class MobileEmitConfig:
    app_name: str = "apex-factory-mobile"
    app_slug: str = "apex-factory-mobile"
    display_name: str = "APEX Mobile"
    description: str = "Generated by APEX FACTORY v6.0 - Mobile target"
    target_src_dir: str = "app"
    components_subdir: str = "components"
    styles_subdir: str = "styles"
    bundle_identifier_ios: str = "com.apexfactory.app"
    package_android: str = "com.apexfactory.app"
    generate_scaffold: bool = True


# ============================================================
# 2. MOBILE EMITTER
# ============================================================

class MobileEmitter(CodeEmitter):
    EMITTER_ID = "react_native"
    TARGET_LANGUAGE = "typescript_react"      # vẫn là TSX

    def __init__(
        self,
        catalog: ComponentCatalog,
        token_registry: TokenRegistry,
        config: Optional[MobileEmitConfig] = None,
    ):
        self.catalog = catalog
        self.registry = token_registry
        self.config = config or MobileEmitConfig()
        self._warnings: List[str] = []

    @enforce_principle_v6(PrincipleV6.NT11_DESIGN_SYSTEM_INTEGRITY)
    @enforce_principle_v6(PrincipleV6.NT12_ACCESSIBILITY_NON_NEGOTIABLE)
    def emit_graph(self, graph: DesignGraph) -> EmitResult:
        self._warnings = []
        if graph.target != RenderTarget.REACT_NATIVE:
            self._warnings.append(
                f"Graph target={graph.target.value} khác REACT_NATIVE"
            )

        files: List[FileModule] = []
        used_ids: Set[str] = {n.component_id for n in graph.nodes.values()}

        # 1. Component files (skip HTML - những cái này map sang RN primitive dùng trực tiếp)
        for cid in sorted(used_ids):
            if cid in HTML_TO_RN:
                continue
            mod = self._build_component_file(cid)
            if mod:
                files.append(mod)

        # 2. App.tsx + index.ts
        files.append(self._build_app_file(graph, used_ids))
        files.append(self._build_index_ts())

        # 3. Scaffold
        scaffold: Dict[str, str] = {}
        if self.config.generate_scaffold:
            tw_builder = TailwindConfigBuilder(self.registry)
            scaffold["tailwind.config.js"] = self._render_tailwind_config_rn(tw_builder)
            scaffold[f"{self.config.target_src_dir}/{self.config.styles_subdir}/global.css"] = (
                tw_builder.render_css_variables()
                + "\n@tailwind base;\n@tailwind components;\n@tailwind utilities;\n"
            )
            scaffold["babel.config.js"] = self._render_babel_config()
            scaffold["metro.config.js"] = self._render_metro_config()
            scaffold["app.json"] = self._render_app_json()
            scaffold["package.json"] = self._render_package_json()
            scaffold["tsconfig.json"] = self._render_tsconfig()
            scaffold["nativewind-env.d.ts"] = '/// <reference types="nativewind/types" />\n'
            scaffold["README.md"] = self._render_readme()

        stats = {
            "component_count": len(used_ids),
            "file_count": len(files),
            "scaffold_count": len(scaffold),
            "placeholder_count": sum(
                1 for n in graph.nodes.values()
                if n.component_id.startswith("placeholder.")
            ),
            "node_count": len(graph.nodes),
        }

        return EmitResult(
            files=files,
            entry_file_path=f"{self.config.target_src_dir}/index.ts",
            scaffold_files=scaffold,
            warnings=list(self._warnings),
            stats=stats,
        )

    # ============================================================
    # 3. COMPONENT FILE
    # ============================================================

    def _build_component_file(self, component_id: str) -> Optional[FileModule]:
        comp_name = to_pascal_case(component_id)
        is_placeholder = component_id.startswith("placeholder.")
        spec = self.catalog.get(component_id)

        file_path = (
            f"{self.config.target_src_dir}/"
            f"{self.config.components_subdir}/"
            f"{comp_name}/{comp_name}.tsx"
        )
        if spec is None and not is_placeholder:
            self._warnings.append(
                f"Component '{component_id}' không trong catalog - stub RN"
            )

        # RN imports
        rn_imports_needed = self._default_rn_tag_for(spec)  # tag name
        imports: List[ImportSpec] = [
            ImportSpec(module="react", default_name="React"),
            ImportSpec(
                module="react-native",
                named_imports=(rn_imports_needed,),
            ),
        ]

        props_iface = self._build_props_interface(comp_name, spec)
        body_jsx = self._build_stub_jsx(component_id, comp_name, spec)

        fn = FunctionDeclaration(
            name=comp_name,
            params=[FunctionParam("props", TSType(f"{comp_name}Props"))],
            return_type=TSType("JSX.Element"),
            return_jsx=body_jsx,
            is_arrow=True,
            is_default_export=True,
        )

        header = (
            f"Component (RN): {component_id}\n"
            f"Generated by APEX FACTORY v6.0 - MobileEmitter {MOBILE_FACTORY_VERSION}"
        )
        if is_placeholder:
            header += "\n!!! PLACEHOLDER - fill trước khi publish."

        return FileModule(
            file_path=file_path,
            language="typescript_react",
            imports=imports,
            top_level=[props_iface, fn],
            header_comment=header,
        )

    def _default_rn_tag_for(self, spec: Optional[ComponentSpec]) -> str:
        if spec is None:
            return "View"
        role = spec.a11y.role.value
        return {
            "button":   "Pressable",
            "link":     "Pressable",
            "heading":  "Text",
            "img":      "Image",
            "form":     "View",
        }.get(role, "View")

    def _build_props_interface(
        self, comp_name: str, spec: Optional[ComponentSpec],
    ) -> TSInterface:
        props: List[TSProperty] = []
        if spec is None:
            props.append(TSProperty("children", TS_REACT_NODE, optional=True))
            props.append(TSProperty("className", TS_STRING, optional=True))
        else:
            for p in spec.prop_schema:
                ts_type = self._prop_to_ts(p)
                props.append(TSProperty(
                    name=p.name, type_=ts_type,
                    optional=not p.required, docstring=p.description,
                ))
            if any(s.name == "default" for s in spec.slots) and not any(
                p.name == "children" for p in props
            ):
                props.append(TSProperty("children", TS_REACT_NODE, optional=True))
            if not any(p.name == "className" for p in props):
                props.append(TSProperty("className", TS_STRING, optional=True))
        return TSInterface(name=f"{comp_name}Props", properties=props)

    def _prop_to_ts(self, prop: PropSchema) -> TSType:
        t = prop.type_hint
        if t == "string":  return TS_STRING
        if t == "number":  return TS_NUMBER
        if t == "boolean": return TS_BOOLEAN
        if t == "node":    return TS_REACT_NODE
        if t == "any":     return TS_ANY
        if t == "enum" and prop.enum_values:
            return TSType(" | ".join(f'"{v}"' for v in prop.enum_values))
        return TS_UNKNOWN

    def _build_stub_jsx(
        self, component_id: str, comp_name: str, spec: Optional[ComponentSpec],
    ) -> JSXNode:
        tag = self._default_rn_tag_for(spec)
        attrs: List[JSXAttribute] = []
        # className (NativeWind)
        attrs.append(JSXAttribute(
            "className",
            'props.className ?? ""',
            is_expression=True,
        ))
        # a11y: RN dùng accessibilityLabel thay aria-label
        if spec:
            role_val = spec.a11y.role.value
            if role_val in ("button", "link", "heading", "img"):
                attrs.append(JSXAttribute(
                    "accessibilityRole", role_val,
                ))
            if "aria-label" in spec.a11y.required_aria:
                attrs.append(JSXAttribute(
                    "accessibilityLabel",
                    "props.accessibilityLabel",
                    is_expression=True,
                ))

        children: List[JSXNode] = [JSXNode.expression("props.children")]
        if component_id.startswith("placeholder."):
            children.append(JSXNode.comment(f"TODO fill placeholder: {component_id}"))

        return JSXNode.element(tag, attributes=attrs, children=children)

    # ============================================================
    # 4. APP.TSX
    # ============================================================

    def _build_app_file(
        self, graph: DesignGraph, used_ids: Set[str],
    ) -> FileModule:
        imports: List[ImportSpec] = [
            ImportSpec(module="react", default_name="React"),
        ]
        # RN primitives dùng trong app (thu thập từ used_ids)
        rn_tags_used: Set[str] = {"SafeAreaView", "StatusBar"}
        for cid in used_ids:
            if cid in HTML_TO_RN:
                rn_tags_used.add(HTML_TO_RN[cid])
        imports.append(ImportSpec(
            module="react-native",
            named_imports=tuple(sorted(rn_tags_used)),
        ))
        # NativeWind global CSS
        imports.append(ImportSpec(
            module=f"./{self.config.styles_subdir}/global.css",
            side_effect_only=True,
        ))

        # Component imports
        for cid in sorted(used_ids):
            if cid in HTML_TO_RN:
                continue
            name = to_pascal_case(cid)
            imports.append(ImportSpec(
                module=f"./{self.config.components_subdir}/{name}/{name}",
                default_name=name,
            ))

        # Data hooks
        body_stmts = self._build_data_hooks(graph)

        # JSX: wrap root inside SafeAreaView + StatusBar
        root_jsx_inner = self._node_to_jsx(graph.get_root(), graph, depth=0)
        root_jsx = JSXNode.element(
            "SafeAreaView",
            attributes=[JSXAttribute("className", "flex-1 bg-background")],
            children=[
                JSXNode.element("StatusBar", attributes=[
                    JSXAttribute("barStyle", "default"),
                ], self_closing=True),
                root_jsx_inner,
            ],
        )

        app_fn = FunctionDeclaration(
            name="App",
            params=[],
            return_type=TSType("JSX.Element"),
            body_statements=body_stmts,
            return_jsx=root_jsx,
            is_default_export=True,
            is_arrow=True,
        )

        return FileModule(
            file_path=f"{self.config.target_src_dir}/App.tsx",
            language="typescript_react",
            imports=imports,
            top_level=[app_fn],
            header_comment=(
                f"App root (RN) - DesignGraph {graph.graph_id}"
            ),
        )

    def _build_data_hooks(self, graph: DesignGraph) -> List[str]:
        stmts: List[str] = []
        for ds_id, ds in graph.data_sources.items():
            var = to_camel_case(ds_id)
            if ds.kind == DataSourceKind.STATE:
                init = ds.config.get("initial", None)
                init_str = json.dumps(init, ensure_ascii=False) if init is not None else "undefined"
                stmts.append(
                    f"const [{var}, set{to_pascal_case(ds_id)}] = "
                    f"React.useState<{ds.shape_hint}>({init_str});"
                )
            elif ds.kind == DataSourceKind.STATIC:
                raw = json.dumps(ds.config.get("value"), ensure_ascii=False)
                stmts.append(f"const {var}: {ds.shape_hint} = {raw};")
            elif ds.kind == DataSourceKind.REST:
                url = ds.config.get("url", "/api/unknown")
                stmts.append(
                    f"// TODO RN REST: {var} (use react-query / fetch + useEffect). URL={url}"
                )
                stmts.append(
                    f"const [{var}, set{to_pascal_case(ds_id)}] = "
                    f"React.useState<{ds.shape_hint} | null>(null);"
                )
        return stmts

    # ============================================================
    # 5. NODE → JSX
    # ============================================================

    def _node_to_jsx(
        self, node: DesignNode, graph: DesignGraph, depth: int = 0,
    ) -> JSXNode:
        if depth > 20:
            return JSXNode.comment(f"Max depth at {node.node_id}")
        # Tag resolve: HTML → RN primitive, else PascalCase
        if node.component_id in HTML_TO_RN:
            tag = HTML_TO_RN[node.component_id]
        else:
            tag = to_pascal_case(node.component_id)

        attrs = self._build_node_attrs(node)

        children_jsx: List[JSXNode] = []
        slot_order = ["default"] + [s for s in node.children_by_slot if s != "default"]
        for slot_name in slot_order:
            for child_id in node.children_by_slot.get(slot_name, []):
                child = graph.nodes.get(child_id)
                if child is None:
                    continue
                children_jsx.append(self._node_to_jsx(child, graph, depth + 1))

        if node.component_id.startswith("placeholder."):
            children_jsx.insert(0, JSXNode.comment(
                f"placeholder {node.metadata.get('feature_id', 'unknown')} - RN fill needed"
            ))

        return JSXNode.element(tag=tag, attributes=attrs, children=children_jsx)

    def _build_node_attrs(self, node: DesignNode) -> List[JSXAttribute]:
        attrs: List[JSXAttribute] = []
        attrs.append(JSXAttribute("key", node.node_id))

        # RN: button onClick → onPress, không có href
        for prop_name, value in node.props.items():
            if prop_name == "children":
                continue
            # Rename web-specific props
            rn_prop = self._rename_web_to_rn(prop_name)
            rendered, is_expr = to_jsx_value(value)
            attrs.append(JSXAttribute(rn_prop, rendered, is_expression=is_expr))

        for prop_name, source_id in node.data_bindings.items():
            rn_prop = self._rename_web_to_rn(prop_name)
            attrs.append(JSXAttribute(
                rn_prop, to_camel_case(source_id), is_expression=True,
            ))

        for ev_name, handler in node.event_handlers.items():
            rn_ev = self._rename_web_to_rn(ev_name)
            attrs.append(JSXAttribute(rn_ev, handler, is_expression=True))

        # className via NativeWind
        cl = ClassList()
        base = node.props.get("className")
        if isinstance(base, str):
            cl.add(base)
        for bp, ov in node.responsive_overrides.items():
            if isinstance(ov, dict):
                bc = ov.get("className")
                if isinstance(bc, str):
                    # NativeWind v4: sm:, md:, lg: vẫn work
                    for tk in bc.split():
                        cl.add(f"{bp}:{tk}")
        if cl.to_list():
            attrs.append(JSXAttribute("className", cl.render()))

        return attrs

    @staticmethod
    def _rename_web_to_rn(prop_name: str) -> str:
        return {
            "onClick":   "onPress",
            "onMouseOver": "onPressIn",
            "onMouseOut":  "onPressOut",
            "href":      "onPress",      # partial - developer review
            "src":       "source",       # Image
        }.get(prop_name, prop_name)

    # ============================================================
    # 6. index.ts + SCAFFOLD
    # ============================================================

    def _build_index_ts(self) -> FileModule:
        content = (
            "// APEX FACTORY v6.0 - RN entry point (Expo)\n"
            "import { registerRootComponent } from 'expo';\n"
            "import App from './App';\n"
            "registerRootComponent(App);\n"
        )
        mod = FileModule(
            file_path=f"{self.config.target_src_dir}/index.ts",
            language="typescript",
        )
        mod.top_level.append(content)
        mod.trailing_newline = False
        return mod

    def _render_tailwind_config_rn(self, builder: TailwindConfigBuilder) -> str:
        """Tailwind config cho NativeWind - content paths khác."""
        theme = builder.build_theme()
        extend_dict = theme.to_dict()
        extend_json = json.dumps(extend_dict, indent=2, ensure_ascii=False)
        content_paths = [
            f"./{self.config.target_src_dir}/**/*.{{js,ts,jsx,tsx}}",
        ]
        content_json = json.dumps(content_paths, indent=2)
        return (
            "// Auto-generated by APEX FACTORY v6.0 - MobileEmitter (NativeWind)\n"
            "/** @type {import('tailwindcss').Config} */\n"
            "module.exports = {\n"
            f"  content: {content_json},\n"
            "  presets: [require('nativewind/preset')],\n"
            "  theme: {\n"
            f"    extend: {extend_json}\n"
            "  },\n"
            "  plugins: [],\n"
            "};\n"
        )

    def _render_babel_config(self) -> str:
        return (
            "// APEX FACTORY v6.0 - babel.config.js\n"
            "module.exports = function (api) {\n"
            "  api.cache(true);\n"
            "  return {\n"
            "    presets: [\n"
            "      ['babel-preset-expo', { jsxImportSource: 'nativewind' }],\n"
            "      'nativewind/babel',\n"
            "    ],\n"
            "  };\n"
            "};\n"
        )

    def _render_metro_config(self) -> str:
        return (
            "// APEX FACTORY v6.0 - metro.config.js (NativeWind v4)\n"
            "const { getDefaultConfig } = require('expo/metro-config');\n"
            "const { withNativeWind } = require('nativewind/metro');\n"
            "const config = getDefaultConfig(__dirname);\n"
            "module.exports = withNativeWind(config, {\n"
            f"  input: './{self.config.target_src_dir}/{self.config.styles_subdir}/global.css',\n"
            "});\n"
        )

    def _render_app_json(self) -> str:
        return json.dumps({
            "expo": {
                "name": self.config.display_name,
                "slug": self.config.app_slug,
                "version": "0.1.0",
                "orientation": "portrait",
                "userInterfaceStyle": "automatic",
                "splash": {
                    "resizeMode": "contain",
                    "backgroundColor": "#ffffff",
                },
                "ios": {
                    "supportsTablet": True,
                    "bundleIdentifier": self.config.bundle_identifier_ios,
                },
                "android": {
                    "package": self.config.package_android,
                    "adaptiveIcon": {"backgroundColor": "#ffffff"},
                },
                "web": {"bundler": "metro"},
            },
        }, indent=2) + "\n"

    def _render_package_json(self) -> str:
        return json.dumps({
            "name": self.config.app_name,
            "version": "0.1.0",
            "main": f"{self.config.target_src_dir}/index.ts",
            "scripts": {
                "start": "expo start",
                "android": "expo start --android",
                "ios": "expo start --ios",
                "web": "expo start --web",
                "typecheck": "tsc --noEmit",
            },
            "dependencies": {
                "expo": EXPO_SDK_VERSION,
                "expo-status-bar": "~1.12.1",
                "react": REACT_VERSION_RN,
                "react-native": RN_VERSION,
                "nativewind": NATIVEWIND_VERSION,
                "react-native-reanimated": "~3.10.1",
                "react-native-safe-area-context": "4.10.5",
            },
            "devDependencies": {
                "@babel/core": "^7.24.0",
                "@types/react": "~18.2.79",
                "tailwindcss": "^3.4.3",
                "typescript": "^5.4.5",
            },
            "engines": {"node": ">=18.0.0"},
            "private": True,
        }, indent=2) + "\n"

    def _render_tsconfig(self) -> str:
        return json.dumps({
            "extends": "expo/tsconfig.base",
            "compilerOptions": {
                "strict": True,
                "jsx": "react-jsx",
                "jsxImportSource": "nativewind",
            },
            "include": [
                f"{self.config.target_src_dir}/**/*",
                "nativewind-env.d.ts",
            ],
        }, indent=2) + "\n"

    def _render_readme(self) -> str:
        return (
            f"# {self.config.display_name}\n\n"
            f"{self.config.description}\n\n"
            "Auto-generated by **APEX FACTORY v6.0 - MobileEmitter**.\n\n"
            "## Chạy dev\n\n"
            "```bash\n"
            "npm install\n"
            "npx expo start\n"
            "```\n\n"
            "- iOS: bấm `i` ở terminal Expo (cần Xcode simulator)\n"
            "- Android: bấm `a` (cần Android emulator)\n"
            "- Web: `npm run web`\n\n"
            "## Ghi chú\n"
            "- NativeWind v4: className dùng Tailwind syntax trực tiếp.\n"
            "- Placeholder components cần fill trước khi publish.\n"
        )


# ============================================================
# 7. MOBILE FACTORY FACADE (optional quick wrapper)
# ============================================================

@dataclass
class MobileFactoryConfig:
    emit_config: MobileEmitConfig = field(default_factory=MobileEmitConfig)
    project_id: Optional[str] = None


class MobileFactory:
    """Facade nhẹ cho target mobile - hiện tại chỉ wrap MobileEmitter."""

    def __init__(
        self,
        *,
        component_catalog: ComponentCatalog,
        token_registry: TokenRegistry,
        config: Optional[MobileFactoryConfig] = None,
    ):
        self.catalog = component_catalog
        self.registry = token_registry
        self.config = config or MobileFactoryConfig()
        self.emitter = MobileEmitter(
            catalog=component_catalog,
            token_registry=token_registry,
            config=self.config.emit_config,
        )

    def build_from_graph(self, graph: DesignGraph) -> EmitResult:
        """Minimum: Graph → EmitResult (C2 tự chạy qua Commander nếu muốn)."""
        return self.emitter.emit_graph(graph)


# ============================================================
# 8. SANITY CHECK
# ============================================================

def mobile_factory_sanity_check() -> Dict[str, bool]:
    from apex_core.foundation.ontology_ui import (
        A11yContract,
        A11yRole,
        ColorToken,
        ComponentCategory,
        ComponentSpec,
        ComponentState,
        PropSchema,
        TokenRole,
    )
    from apex_core.foundation.ui_ir import DesignNode

    checks: Dict[str, bool] = {}

    catalog = ComponentCatalog()
    catalog.register(ComponentSpec(
        component_id="atom.button.primary",
        label="Btn",
        category=ComponentCategory.ATOM,
        prop_schema=(PropSchema("label", "string", required=True),),
        slots=(),
        states=(ComponentState.DEFAULT,),
        a11y=A11yContract(
            role=A11yRole.BUTTON,
            keyboard_map=(("Enter", "activate"),),
        ),
        design_tokens_used=(),
        dependencies=(),
        render_targets=(RenderTarget.REACT_NATIVE,),
    ))
    registry = TokenRegistry()
    registry.add(ColorToken(
        token_id="c.primary", value="#2563EB", role=TokenRole.PRIMARY,
    ))
    registry.freeze()

    g = DesignGraph(graph_id="g_m", target=RenderTarget.REACT_NATIVE, root_id="root")
    g.add_node(DesignNode(node_id="root", component_id="div"))
    g.add_node(DesignNode(
        node_id="b", component_id="atom.button.primary",
        props={"label": "Tap me"},
        event_handlers={"onClick": "() => console.log('tap')"},
    ))
    g.link("root", "default", "b")

    factory = MobileFactory(
        component_catalog=catalog, token_registry=registry,
    )
    result = factory.build_from_graph(g)

    checks["result_ok"] = isinstance(result, EmitResult)
    checks["has_app_tsx"] = any(f.file_path.endswith("App.tsx") for f in result.files)
    checks["has_index_ts"] = any(f.file_path.endswith("index.ts") for f in result.files)
    checks["has_app_json"] = "app.json" in result.scaffold_files
    checks["has_babel"] = "babel.config.js" in result.scaffold_files
    checks["has_metro"] = "metro.config.js" in result.scaffold_files
    checks["has_nativewind_types"] = "nativewind-env.d.ts" in result.scaffold_files

    # App.tsx render: div → View, import SafeAreaView, onClick → onPress
    app_file = next(f for f in result.files if f.file_path.endswith("App.tsx"))
    rendered = app_file.render()
    checks["app_uses_view"] = "<View" in rendered
    checks["app_has_safearea"] = "SafeAreaView" in rendered
    checks["app_renamed_to_onpress"] = "onPress={" in rendered
    checks["app_no_div"] = "<div" not in rendered

    # Package json: expo + react-native + nativewind
    pkg = json.loads(result.scaffold_files["package.json"])
    checks["pkg_expo"] = "expo" in pkg["dependencies"]
    checks["pkg_rn"] = "react-native" in pkg["dependencies"]
    checks["pkg_nativewind"] = "nativewind" in pkg["dependencies"]

    # Babel config có nativewind preset
    babel = result.scaffold_files["babel.config.js"]
    checks["babel_has_nativewind"] = "nativewind/babel" in babel

    return checks


__all__ = [
    "MOBILE_FACTORY_VERSION",
    "EXPO_SDK_VERSION", "RN_VERSION", "NATIVEWIND_VERSION",
    "HTML_TO_RN", "RN_BUILTIN_COMPONENTS",
    "MobileEmitConfig", "MobileEmitter",
    "MobileFactoryConfig", "MobileFactory",
    "mobile_factory_sanity_check",
]
