"""
APEX FACTORY v6.0 - Factory Layer
File: web_factory.py

Mục đích: Facade production-ready cho target WEB.
    Nối toàn bộ pipeline end-to-end:
      Brief → B6 Commander (B1→B2→B3→B4) → Radar 4D → Round Table V6
            → Quality Gate → ReactEmitter → PreviewSandbox → BuildArtifact

    Một class duy nhất `WebFactory` với 1 method chính `.build(raw_brief)`.

Cấu trúc kết quả:
    BuildArtifact chứa:
      - quality_decision : APPROVED / REVISION / REJECTED
      - emit_result      : EmitResult (source files React)
      - sandbox_report   : SandboxReport (bundle đo thật)
      - best_variant_id  : graph_id của variant tốt nhất
      - fix_proposals    : list FixProposal từ QualityGate

Triết lý NT5:
    Build KHÔNG auto-deploy. Artifact ra + chờ C2 review + token → deploy_adapter.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence

from apex_core.brains_v6.b6_commander import B6Commander, CommanderConfig
from apex_core.brains_v6.brain_base_v6 import FactoryBrainContext
from apex_core.deliberation_v6.quality_gate import (
    FixProposal,
    QualityDecision,
    QualityDecisionStatus,
    QualityGate,
    QualityGateThresholds,
)
from apex_core.deliberation_v6.radar_4d import (
    Radar4DReport,
    Radar4DScorer,
)
from apex_core.deliberation_v6.ui_critics import (
    CriticInput,
    RoundTableV6,
    RoundTableV6Report,
)
from apex_core.emitters.react_emitter import (
    EmitConfig,
    EmitResult,
    ReactEmitter,
)
from apex_core.external.llm_broker import LLMBroker
from apex_core.foundation.domain_types import DomainType
from apex_core.foundation.ontology_ui import ComponentCatalog, TokenRegistry
from apex_core.foundation.principles_v6 import (
    PrincipleV6,
    enforce_principle_v6,
)
from apex_core.foundation.project_snapshot import ProjectLineage
from apex_core.foundation.ui_ir import DesignGraph
from apex_core.ui_v6.preview_sandbox import (
    PreviewSandbox,
    SandboxConfig,
    SandboxMode,
    SandboxReport,
)

# ============================================================
# 0. VERSION
# ============================================================

WEB_FACTORY_VERSION = "6.0.0"


# ============================================================
# 1. CONFIG
# ============================================================

@dataclass
class WebFactoryConfig:
    app_name: str = "apex-factory-web-app"
    app_title: str = "APEX Factory Web App"
    description: str = "Generated by APEX FACTORY v6.0"

    # Pipeline behavior
    run_sandbox: bool = True
    sandbox_mode: SandboxMode = SandboxMode.DRY_RUN      # DRY_RUN = an toàn default
    pick_variant_policy: str = "best_quality"            # "best_quality" | "baseline" | "first"
    quality_thresholds: Optional[QualityGateThresholds] = None

    # Project identity
    project_id: Optional[str] = None

    # Deployment target (để BuildArtifact track)
    output_root_dir: Optional[str] = None


# ============================================================
# 2. RESULT TYPES
# ============================================================

class BuildStatus(str, Enum):
    SUCCESS = "success"
    BLOCKED_AT_COMMANDER = "blocked_at_commander"
    BLOCKED_AT_GATE = "blocked_at_gate"
    REVISION_REQUIRED = "revision_required"
    SANDBOX_FAILED = "sandbox_failed"
    ERROR = "error"


@dataclass
class VariantEvaluation:
    """1 variant sau khi chạy Radar + Round Table + Gate."""
    graph_id: str
    variant_strategy: str
    radar_report: Dict[str, Any]
    round_table_report: Dict[str, Any]
    quality_decision: Dict[str, Any]
    composite_quality: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class BuildArtifact:
    build_id: str
    status: BuildStatus
    started_at_utc: str
    finished_at_utc: str
    elapsed_sec: float

    # Brief digest
    brief_id: Optional[str] = None
    brief_summary: Optional[str] = None

    # Variants + chọn best
    variants_evaluated: List[VariantEvaluation] = field(default_factory=list)
    best_variant_id: Optional[str] = None
    best_variant_graph: Optional[DesignGraph] = None

    # Final emit + sandbox
    emit_result: Optional[EmitResult] = None
    sandbox_report: Optional[SandboxReport] = None

    # Actionable
    fix_proposals: List[FixProposal] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    # Audit
    commander_log: List[Dict[str, Any]] = field(default_factory=list)
    llm_calls: int = 0

    def is_success(self) -> bool:
        return self.status == BuildStatus.SUCCESS

    def to_dict(self) -> Dict[str, Any]:
        return {
            "build_id": self.build_id,
            "status": self.status.value,
            "started_at_utc": self.started_at_utc,
            "finished_at_utc": self.finished_at_utc,
            "elapsed_sec": round(self.elapsed_sec, 2),
            "brief_id": self.brief_id,
            "brief_summary": self.brief_summary,
            "variants_evaluated": [v.to_dict() for v in self.variants_evaluated],
            "best_variant_id": self.best_variant_id,
            "emit_stats": self.emit_result.stats if self.emit_result else None,
            "sandbox_report": (
                self.sandbox_report.to_dict() if self.sandbox_report else None
            ),
            "fix_proposals": [fp.to_dict() for fp in self.fix_proposals],
            "warnings": list(self.warnings),
            "errors": list(self.errors),
            "commander_log": list(self.commander_log),
            "llm_calls": self.llm_calls,
        }


# ============================================================
# 3. WEB FACTORY (main facade)
# ============================================================

class WebFactory:
    """
    Production facade cho Web. C2 chỉ cần:

        factory = WebFactory(catalog, token_registry, config)
        artifact = factory.build(raw_brief="Tôi cần landing...")
        if artifact.is_success():
            artifact.emit_result.write_to_disk("./output")
    """

    def __init__(
        self,
        *,
        component_catalog: ComponentCatalog,
        token_registry: TokenRegistry,
        config: Optional[WebFactoryConfig] = None,
        llm_broker: Optional[LLMBroker] = None,
        project_lineage: Optional[ProjectLineage] = None,
    ):
        self.catalog = component_catalog
        self.registry = token_registry
        self.config = config or WebFactoryConfig()
        self.llm_broker = llm_broker
        self.lineage = project_lineage

        # Sub-components (lazy init)
        self._commander: Optional[B6Commander] = None
        self._radar: Optional[Radar4DScorer] = None
        self._round_table: Optional[RoundTableV6] = None
        self._gate: Optional[QualityGate] = None
        self._emitter: Optional[ReactEmitter] = None
        self._sandbox: Optional[PreviewSandbox] = None

    # -------- Lazy components --------

    def _get_commander(self) -> B6Commander:
        if self._commander is None:
            self._commander = B6Commander(
                config=CommanderConfig(
                    emit_snapshot=False,     # Factory tự quản snapshot
                    fill_placeholders_via_llm=self.llm_broker is not None,
                    abort_on_b3_blocking=True,
                ),
            )
        return self._commander

    def _get_radar(self) -> Radar4DScorer:
        if self._radar is None:
            self._radar = Radar4DScorer()
        return self._radar

    def _get_round_table(self) -> RoundTableV6:
        if self._round_table is None:
            self._round_table = RoundTableV6()
        return self._round_table

    def _get_gate(self) -> QualityGate:
        if self._gate is None:
            self._gate = QualityGate(
                thresholds=self.config.quality_thresholds,
            )
        return self._gate

    def _get_emitter(self) -> ReactEmitter:
        if self._emitter is None:
            self._emitter = ReactEmitter(
                catalog=self.catalog,
                token_registry=self.registry,
                config=EmitConfig(
                    app_name=self.config.app_name,
                    app_title=self.config.app_title,
                    description=self.config.description,
                ),
            )
        return self._emitter

    def _get_sandbox(self) -> PreviewSandbox:
        if self._sandbox is None:
            self._sandbox = PreviewSandbox(SandboxConfig(
                mode=self.config.sandbox_mode,
                working_dir=self.config.output_root_dir,
                keep_on_success=True,
            ))
        return self._sandbox

    # -------- MAIN PIPELINE --------

    @enforce_principle_v6(PrincipleV6.NT1_MULTI_AXIS_CONVERGENCE)
    @enforce_principle_v6(PrincipleV6.NT5_HUMAN_SUPREMACY)
    def build(
        self,
        raw_brief: str,
        c2_signal: Optional[str] = None,
    ) -> BuildArtifact:
        from apex_core.foundation.contracts import now_utc_iso

        t0 = time.perf_counter()
        started = now_utc_iso()
        build_id = f"build_{uuid.uuid4().hex[:12]}"
        project_id = self.config.project_id or f"proj_{uuid.uuid4().hex[:10]}"

        artifact = BuildArtifact(
            build_id=build_id,
            status=BuildStatus.SUCCESS,
            started_at_utc=started,
            finished_at_utc="",
            elapsed_sec=0.0,
        )

        # --- 1. Prepare Commander context ---
        ctx = FactoryBrainContext(
            run_id=build_id,
            current_date=started[:10],
            draws=[],
            current_idx=0,
            project_id=project_id,
            component_catalog=self.catalog,
            token_registry=self.registry,
            llm_broker=self.llm_broker,
            snapshot_lineage=self.lineage,
            target_domain=DomainType.WEB,
            shared_memory={"raw_brief": raw_brief},
        )

        # --- 2. Commander chạy B1→B2→B3→B4 ---
        cmd_result = self._get_commander().run(ctx)
        artifact.commander_log = cmd_result.outputs.get("orchestration_log", [])
        artifact.llm_calls += cmd_result.llm_calls
        if ctx.brief_spec is not None:
            artifact.brief_id = ctx.brief_spec.brief_id
            artifact.brief_summary = ctx.brief_spec.raw_text[:200]

        if not cmd_result.success:
            artifact.errors.extend(cmd_result.errors)
            artifact.warnings.extend(cmd_result.warnings)
            return self._finalize(artifact, BuildStatus.BLOCKED_AT_COMMANDER, t0)

        if not ctx.variant_graphs:
            artifact.errors.append("commander_produced_no_variants")
            return self._finalize(artifact, BuildStatus.BLOCKED_AT_COMMANDER, t0)

        # --- 3. Evaluate từng variant qua Radar + Round Table ---
        evaluations: List[VariantEvaluation] = []
        radar_reports: List[Radar4DReport] = []
        rt_reports: List[RoundTableV6Report] = []

        brief_constraints_for_radar = dict(
            ctx.brief_spec.constraints if ctx.brief_spec else {}
        )
        brief_constraints_for_radar["_product_type"] = (
            ctx.brief_spec.product_type if ctx.brief_spec else ""
        )

        for graph in ctx.variant_graphs:
            radar = self._get_radar().evaluate(
                graph, self.catalog, brief_constraints_for_radar,
            )
            radar_reports.append(radar)

            rt = self._get_round_table().deliberate(CriticInput(
                graph=graph,
                catalog=self.catalog,
                radar_report=radar,
                brief_constraints=dict(ctx.brief_spec.constraints) if ctx.brief_spec else {},
                brief_tone=tuple(ctx.brief_spec.tone) if ctx.brief_spec else (),
                brief_product_type=(
                    ctx.brief_spec.product_type if ctx.brief_spec else ""
                ),
            ))
            rt_reports.append(rt)

        # --- 4. Quality Gate: đánh giá từng variant + chọn best ---
        critique_score = (
            ctx.shared_memory.get("critique_report", {}).get("health_score", 1.0)
        )
        best_decision, all_decisions = self._get_gate().evaluate_variants(
            variant_radar_reports=radar_reports,
            variant_round_tables=rt_reports,
            critique_health_score=critique_score,
            c2_signal=c2_signal,
        )

        for graph, radar, rt, decision in zip(
            ctx.variant_graphs, radar_reports, rt_reports, all_decisions,
        ):
            evaluations.append(VariantEvaluation(
                graph_id=graph.graph_id,
                variant_strategy=str(graph.metadata.get("variant_strategy", "n/a")),
                radar_report=radar.to_dict(),
                round_table_report=rt.to_dict(),
                quality_decision=decision.to_dict(),
                composite_quality=decision.composite_quality,
            ))
        artifact.variants_evaluated = evaluations

        if best_decision is None:
            # Mọi variant đều REJECTED/ABSTAIN - thu thập fix proposals từ variant "đỡ tệ nhất"
            least_bad = min(
                all_decisions,
                key=lambda d: -d.composite_quality,
            ) if all_decisions else None
            if least_bad:
                artifact.fix_proposals = list(least_bad.fix_proposals)
                artifact.errors.append(
                    f"All variants rejected/abstained. Top decision status: "
                    f"{least_bad.status.value}"
                )
            return self._finalize(artifact, BuildStatus.BLOCKED_AT_GATE, t0)

        # Chọn variant theo policy
        chosen_graph = self._pick_variant(
            ctx.variant_graphs, all_decisions, radar_reports, rt_reports,
        )
        chosen_decision = next(
            (d for d in all_decisions if d.graph_id == chosen_graph.graph_id),
            best_decision,
        )
        artifact.best_variant_id = chosen_graph.graph_id
        artifact.best_variant_graph = chosen_graph
        artifact.fix_proposals = list(chosen_decision.fix_proposals)

        revision_required = (
            chosen_decision.status == QualityDecisionStatus.REVISION_REQUIRED
        )
        if revision_required:
            artifact.warnings.append(
                f"Chosen variant requires revision: {chosen_decision.message}"
            )

        # --- 5. Emit code React ---
        try:
            emit_result = self._get_emitter().emit_graph(chosen_graph)
        except Exception as e:
            artifact.errors.append(
                f"emit_failed: {type(e).__name__}: {e}"
            )
            return self._finalize(artifact, BuildStatus.ERROR, t0)
        artifact.emit_result = emit_result
        artifact.warnings.extend(emit_result.warnings)

        # --- 6. Sandbox (optional) ---
        if self.config.run_sandbox:
            sb = self._get_sandbox()
            sandbox_report = sb.run(emit_result)
            artifact.sandbox_report = sandbox_report
            if not sandbox_report.is_success():
                artifact.warnings.append(
                    f"sandbox_status: {sandbox_report.status.value}"
                )

        # --- 7. Final status ---
        final_status = (
            BuildStatus.REVISION_REQUIRED if revision_required
            else BuildStatus.SUCCESS
        )
        return self._finalize(artifact, final_status, t0)

    # -------- Variant picker --------

    def _pick_variant(
        self,
        graphs: Sequence[DesignGraph],
        decisions: Sequence[QualityDecision],
        radar_reports: Sequence[Radar4DReport],
        rt_reports: Sequence[RoundTableV6Report],
    ) -> DesignGraph:
        policy = self.config.pick_variant_policy
        if policy == "first":
            return graphs[0]
        if policy == "baseline":
            # Tìm graph có variant_strategy = "A_baseline"
            for g in graphs:
                if g.metadata.get("variant_strategy") == "A_baseline":
                    return g
            return graphs[0]
        # Default: best_quality
        eligible = [
            (g, d) for g, d in zip(graphs, decisions)
            if d.status in (
                QualityDecisionStatus.APPROVED,
                QualityDecisionStatus.REVISION_REQUIRED,
                QualityDecisionStatus.C2_OVERRIDE_APPROVED,
            )
        ]
        if not eligible:
            return graphs[0]
        best = max(eligible, key=lambda gd: gd[1].composite_quality)
        return best[0]

    def _finalize(
        self, artifact: BuildArtifact, status: BuildStatus, t0: float,
    ) -> BuildArtifact:
        from apex_core.foundation.contracts import now_utc_iso
        artifact.status = status
        artifact.finished_at_utc = now_utc_iso()
        artifact.elapsed_sec = time.perf_counter() - t0
        return artifact


# ============================================================
# 4. SANITY CHECK
# ============================================================

def web_factory_sanity_check() -> Dict[str, bool]:
    from apex_core.foundation.ontology_ui import (
        ColorToken,
        TokenRole,
    )

    checks: Dict[str, bool] = {}

    catalog = ComponentCatalog()   # empty → placeholders sẽ được dùng
    registry = TokenRegistry()
    registry.add(ColorToken(
        token_id="c.primary", value="#2563EB", role=TokenRole.PRIMARY,
    ))
    registry.freeze()

    factory = WebFactory(
        component_catalog=catalog,
        token_registry=registry,
        config=WebFactoryConfig(
            run_sandbox=False,
            project_id="test_web",
        ),
    )

    artifact = factory.build(
        raw_brief=(
            "Tôi cần landing page tối giản cho khóa học AI, tone minimal, "
            "navy chủ đạo. Cần navbar, hero, cta, footer. "
            "Bundle tối đa 300kb."
        ),
    )
    checks["artifact_created"] = isinstance(artifact, BuildArtifact)
    checks["has_variants"] = len(artifact.variants_evaluated) >= 1
    checks["emit_result_present"] = artifact.emit_result is not None
    checks["build_id_set"] = bool(artifact.build_id)
    checks["commander_log_nonempty"] = len(artifact.commander_log) >= 3

    # Status phải là một trong các enum hợp lệ
    checks["status_valid"] = artifact.status in BuildStatus

    # to_dict serializable
    try:
        import json as _json
        _json.dumps(artifact.to_dict(), default=str)
        checks["serializable"] = True
    except Exception:
        checks["serializable"] = False

    return checks


__all__ = [
    "WEB_FACTORY_VERSION",
    "WebFactoryConfig",
    "BuildStatus", "VariantEvaluation", "BuildArtifact",
    "WebFactory",
    "web_factory_sanity_check",
]
