"""
APEX FACTORY v6.0 - Emitter Layer
File: react_emitter.py

Mục đích: DesignGraph → dự án React + TypeScript + Tailwind hoàn chỉnh.
    Output của emit_graph():
      - src/App.tsx                     (compose từ root DesignNode)
      - src/components/*/<Name>.tsx     (1 file cho mỗi component_id)
      - src/styles/tokens.css           (CSS vars từ TokenRegistry)
      - tailwind.config.js              (gen từ TokenRegistry)
      - postcss.config.js
      - vite.config.ts
      - tsconfig.json
      - package.json
      - index.html
      - src/main.tsx                    (entry point)

Triết lý:
    - Mỗi placeholder sinh thành component stub với `TODO: fill` comment
    - Data bindings REST → scaffold `useSWR` hook
    - State bindings → `useState` với type từ shape_hint
    - ClassName luôn đi qua ClassResolver (NT11)
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set

from apex_core.emitters.ast_backbone import (
    TS_ANY,
    TS_BOOLEAN,
    TS_NUMBER,
    TS_REACT_NODE,
    TS_STRING,
    TS_UNKNOWN,
    TS_VOID,
    CodeEmitter,
    ConstDeclaration,
    FileModule,
    FunctionDeclaration,
    FunctionParam,
    ImportSpec,
    JSXAttribute,
    JSXNode,
    TSInterface,
    TSProperty,
    TSType,
    to_camel_case,
    to_jsx_value,
    to_pascal_case,
)
from apex_core.emitters.tailwind_stylist import (
    ClassList,
    ClassResolver,
    TailwindConfigBuilder,
)
from apex_core.foundation.ontology_ui import (
    ComponentCatalog,
    ComponentSpec,
    PropSchema,
    RenderTarget,
    TokenRegistry,
)
from apex_core.foundation.principles_v6 import (
    PrincipleV6,
    enforce_principle_v6,
)
from apex_core.foundation.ui_ir import (
    DataSourceKind,
    DesignGraph,
    DesignNode,
)

# ============================================================
# 0. VERSION + CONSTANTS
# ============================================================

REACT_EMITTER_VERSION = "6.0.0"

REACT_VERSION = "^18.2.0"
TYPESCRIPT_VERSION = "^5.4.5"
VITE_VERSION = "^5.2.0"
TAILWIND_VERSION = "^3.4.3"
POSTCSS_VERSION = "^8.4.38"
AUTOPREFIXER_VERSION = "^10.4.19"
SWR_VERSION = "^2.2.5"

# Map HTML tag → React reserved (không phải component tự viết)
HTML_TAGS: Set[str] = {
    "div", "span", "section", "article", "aside", "header", "footer",
    "main", "nav", "h1", "h2", "h3", "h4", "h5", "h6", "p", "a", "button",
    "img", "ul", "ol", "li", "form", "input", "label", "textarea", "select",
    "option", "table", "tr", "td", "th", "thead", "tbody", "picture", "video",
    "source", "figure", "figcaption", "blockquote", "code", "pre",
}


# ============================================================
# 1. EMIT CONFIG + RESULT
# ============================================================

@dataclass
class EmitConfig:
    app_name: str = "apex-factory-app"
    app_title: str = "APEX Factory App"
    description: str = "Generated by APEX FACTORY v6.0"
    target_src_dir: str = "src"
    components_subdir: str = "components"
    styles_subdir: str = "styles"
    generate_scaffold: bool = True              # vite, tsconfig, package.json, ...
    strict_mode: bool = True
    include_swr: bool = True


@dataclass
class EmitResult:
    files: List[FileModule]
    entry_file_path: str
    scaffold_files: Dict[str, str] = field(default_factory=dict)   # path -> raw content
    warnings: List[str] = field(default_factory=list)
    stats: Dict[str, Any] = field(default_factory=dict)

    def all_file_paths(self) -> List[str]:
        return [f.file_path for f in self.files] + list(self.scaffold_files.keys())

    def write_to_disk(self, root_dir: str) -> List[str]:
        """Viết toàn bộ xuống filesystem. Trả về list path đã ghi."""
        from pathlib import Path
        root = Path(root_dir)
        root.mkdir(parents=True, exist_ok=True)
        written: List[str] = []
        for mod in self.files:
            p = root / mod.file_path
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(mod.render(), encoding="utf-8")
            written.append(str(p))
        for path, content in self.scaffold_files.items():
            p = root / path
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            written.append(str(p))
        return written


# ============================================================
# 2. REACT EMITTER (main)
# ============================================================

class ReactEmitter(CodeEmitter):
    EMITTER_ID = "react"
    TARGET_LANGUAGE = "typescript_react"

    def __init__(
        self,
        catalog: ComponentCatalog,
        token_registry: TokenRegistry,
        config: Optional[EmitConfig] = None,
    ):
        self.catalog = catalog
        self.registry = token_registry
        self.config = config or EmitConfig()
        self.resolver = ClassResolver(token_registry)
        self._warnings: List[str] = []

    @enforce_principle_v6(PrincipleV6.NT11_DESIGN_SYSTEM_INTEGRITY)
    @enforce_principle_v6(PrincipleV6.NT12_ACCESSIBILITY_NON_NEGOTIABLE)
    def emit_graph(self, graph: DesignGraph) -> EmitResult:
        self._warnings = []
        if graph.target != RenderTarget.REACT:
            self._warnings.append(
                f"Graph target={graph.target.value} nhưng dùng ReactEmitter - có thể lệch"
            )

        files: List[FileModule] = []

        # 1. Component files (1 file per unique component_id)
        component_ids = self._collect_used_component_ids(graph)
        for cid in sorted(component_ids):
            if self._is_html_tag(cid):
                continue   # HTML primitive, không cần file riêng
            file_mod = self._build_component_file(cid)
            if file_mod:
                files.append(file_mod)

        # 2. App.tsx (root page)
        app_file = self._build_app_file(graph, component_ids)
        files.append(app_file)

        # 3. main.tsx (React entry)
        main_file = self._build_main_file()
        files.append(main_file)

        # 4. Scaffold files
        scaffold: Dict[str, str] = {}
        if self.config.generate_scaffold:
            tailwind_builder = TailwindConfigBuilder(self.registry)
            scaffold["tailwind.config.js"] = tailwind_builder.render_config()
            scaffold["postcss.config.js"] = self._render_postcss_config()
            scaffold[f"{self.config.target_src_dir}/{self.config.styles_subdir}/tokens.css"] = (
                tailwind_builder.render_css_variables()
                + "\n"
                + self._render_tailwind_entry_css()
            )
            scaffold["vite.config.ts"] = self._render_vite_config()
            scaffold["tsconfig.json"] = self._render_tsconfig()
            scaffold["package.json"] = self._render_package_json()
            scaffold["index.html"] = self._render_index_html()
            scaffold[".gitignore"] = self._render_gitignore()
            scaffold["README.md"] = self._render_readme()

        stats = {
            "component_count": len(component_ids),
            "file_count": len(files),
            "scaffold_count": len(scaffold),
            "placeholder_count": sum(
                1 for n in graph.nodes.values()
                if n.component_id.startswith("placeholder.")
            ),
            "data_sources_count": len(graph.data_sources),
            "node_count": len(graph.nodes),
        }

        return EmitResult(
            files=files,
            entry_file_path=f"{self.config.target_src_dir}/main.tsx",
            scaffold_files=scaffold,
            warnings=list(self._warnings),
            stats=stats,
        )

    # ============================================================
    # 3. COMPONENT FILE BUILDING
    # ============================================================

    def _collect_used_component_ids(self, graph: DesignGraph) -> Set[str]:
        return {n.component_id for n in graph.nodes.values()}

    def _is_html_tag(self, component_id: str) -> bool:
        return component_id in HTML_TAGS

    def _build_component_file(self, component_id: str) -> Optional[FileModule]:
        """Sinh 1 .tsx file cho 1 component_id."""
        is_placeholder = component_id.startswith("placeholder.")
        spec = self.catalog.get(component_id)

        component_name = to_pascal_case(component_id)
        file_path = (
            f"{self.config.target_src_dir}/"
            f"{self.config.components_subdir}/"
            f"{component_name}/{component_name}.tsx"
        )

        if spec is None and not is_placeholder:
            self._warnings.append(
                f"Component '{component_id}' không có trong catalog - sinh stub"
            )

        # Build TS Props interface
        props_interface = self._build_props_interface(component_name, spec)

        # Build function body
        jsx_body = self._build_stub_jsx(component_id, component_name, spec)

        # Imports
        imports = [
            ImportSpec(module="react", default_name="React"),
        ]

        fn = FunctionDeclaration(
            name=component_name,
            params=[FunctionParam("props", TSType(f"{component_name}Props"))],
            return_type=TSType("JSX.Element"),
            return_jsx=jsx_body,
            is_arrow=True,
            is_default_export=True,
        )

        header = self._component_header_comment(component_id, spec, is_placeholder)

        return FileModule(
            file_path=file_path,
            language="typescript_react",
            imports=imports,
            top_level=[props_interface, fn],
            header_comment=header,
        )

    def _component_header_comment(
        self,
        component_id: str,
        spec: Optional[ComponentSpec],
        is_placeholder: bool,
    ) -> str:
        lines = [
            f"Component: {component_id}",
            f"Generated by APEX FACTORY v6.0 - ReactEmitter {REACT_EMITTER_VERSION}",
        ]
        if spec:
            lines.append(f"Category: {spec.category.value}")
            lines.append(f"Version: {spec.version}")
            if spec.a11y.role.value != "none":
                lines.append(f"A11y role: {spec.a11y.role.value}")
        if is_placeholder:
            lines.append("")
            lines.append("!!! PLACEHOLDER - Cần fill logic thực tế trước khi publish.")
            lines.append("Action: gọi B6 Commander với LLM broker hoặc tự implement.")
        return "\n".join(lines)

    def _build_props_interface(
        self,
        component_name: str,
        spec: Optional[ComponentSpec],
    ) -> TSInterface:
        properties: List[TSProperty] = []
        if spec is None:
            # Stub interface: children + className tối thiểu
            properties.append(TSProperty("children", TS_REACT_NODE, optional=True))
            properties.append(TSProperty("className", TS_STRING, optional=True))
        else:
            for prop in spec.prop_schema:
                ts_type = self._prop_to_ts_type(prop)
                properties.append(TSProperty(
                    name=prop.name,
                    type_=ts_type,
                    optional=not prop.required,
                    docstring=prop.description,
                ))
            # Nếu spec có slots, thêm children cho slot "default"
            has_default_slot = any(s.name == "default" for s in spec.slots)
            if has_default_slot and not any(p.name == "children" for p in properties):
                properties.append(TSProperty("children", TS_REACT_NODE, optional=True))
            # className luôn có
            if not any(p.name == "className" for p in properties):
                properties.append(TSProperty("className", TS_STRING, optional=True))

        return TSInterface(
            name=f"{component_name}Props",
            properties=properties,
        )

    def _prop_to_ts_type(self, prop: PropSchema) -> TSType:
        t = prop.type_hint
        if t == "string":
            return TS_STRING
        if t == "number":
            return TS_NUMBER
        if t == "boolean":
            return TS_BOOLEAN
        if t == "node":
            return TS_REACT_NODE
        if t == "any":
            return TS_ANY
        if t == "enum":
            if prop.enum_values:
                return TSType(" | ".join(f'"{v}"' for v in prop.enum_values))
            return TS_STRING
        return TS_UNKNOWN

    def _build_stub_jsx(
        self,
        component_id: str,
        component_name: str,
        spec: Optional[ComponentSpec],
    ) -> JSXNode:
        """Body JSX mặc định cho component file (wrapper đơn giản)."""
        wrapper_tag = self._default_html_tag_for(spec)
        cls = self._default_class_list_for(spec)

        attrs: List[JSXAttribute] = []
        if cls:
            attrs.append(JSXAttribute(
                "className",
                f'`${{props.className ?? ""}} {cls}`.trim()',
                is_expression=True,
            ))

        # A11y role attr nếu có
        if spec and spec.a11y.role.value not in ("none", "heading"):
            attrs.append(JSXAttribute("role", spec.a11y.role.value))

        # aria-label nếu required
        if spec:
            for aria_name in spec.a11y.required_aria:
                if aria_name == "aria-label":
                    attrs.append(JSXAttribute(
                        "aria-label", "props.ariaLabel", is_expression=True,
                    ))

        children: List[JSXNode] = []
        children.append(JSXNode.expression("props.children"))
        if component_id.startswith("placeholder."):
            children.append(JSXNode.comment(f"TODO fill placeholder: {component_id}"))

        return JSXNode.element(
            wrapper_tag, attributes=attrs, children=children,
        )

    def _default_html_tag_for(self, spec: Optional[ComponentSpec]) -> str:
        if spec is None:
            return "div"
        role = spec.a11y.role.value
        return {
            "navigation": "nav",
            "banner":     "header",
            "contentinfo": "footer",
            "main":       "main",
            "article":    "article",
            "region":     "section",
            "list":       "ul",
            "listitem":   "li",
            "button":     "button",
            "link":       "a",
            "form":       "form",
            "heading":    "h2",    # default h2; component gen h1 khi level=1
            "img":        "img",
        }.get(role, "div")

    def _default_class_list_for(self, spec: Optional[ComponentSpec]) -> str:
        """Class list mặc định dựa trên design_tokens_used của spec."""
        if spec is None:
            return ""
        cl = ClassList()
        for tid in spec.design_tokens_used:
            tok = self.registry.get(tid)
            if tok is None:
                continue
            # Map crude: ColorToken với role=text → "text-<slug>", role=background → "bg-<slug>"
            from apex_core.emitters.tailwind_stylist import _slugify_token_id
            from apex_core.foundation.ontology_ui import ColorToken, TokenRole
            if isinstance(tok, ColorToken):
                slug = _slugify_token_id(tid)
                if tok.role in (TokenRole.BACKGROUND, TokenRole.SURFACE, TokenRole.SURFACE_ALT):
                    cl.add(f"bg-{slug}")
                elif tok.role in (TokenRole.TEXT, TokenRole.TEXT_MUTED):
                    cl.add(f"text-{slug}")
                elif tok.role == TokenRole.BORDER:
                    cl.add("border", f"border-{slug}")
                elif tok.role == TokenRole.PRIMARY:
                    cl.add(f"bg-{slug}", "text-white")
        return cl.render()

    # ============================================================
    # 4. APP.TSX (ROOT FILE)
    # ============================================================

    def _build_app_file(
        self,
        graph: DesignGraph,
        used_component_ids: Set[str],
    ) -> FileModule:
        imports: List[ImportSpec] = [
            ImportSpec(module="react", default_name="React"),
        ]
        imports.append(ImportSpec(
            module=f"./{self.config.styles_subdir}/tokens.css",
            side_effect_only=True,
        ))

        # Data sources → hooks imports
        needs_swr = any(
            ds.kind == DataSourceKind.REST for ds in graph.data_sources.values()
        )
        if needs_swr and self.config.include_swr:
            imports.append(ImportSpec(module="swr", default_name="useSWR"))

        # Import component files
        for cid in sorted(used_component_ids):
            if self._is_html_tag(cid):
                continue
            comp_name = to_pascal_case(cid)
            imports.append(ImportSpec(
                module=f"./{self.config.components_subdir}/{comp_name}/{comp_name}",
                default_name=comp_name,
            ))

        # Body statements: data hooks
        body_stmts = self._build_data_hook_statements(graph)

        # JSX from graph root
        root_jsx = self._node_to_jsx(graph.get_root(), graph, depth=0)

        app_fn = FunctionDeclaration(
            name="App",
            params=[],
            return_type=TSType("JSX.Element"),
            body_statements=body_stmts,
            return_jsx=root_jsx,
            is_default_export=True,
            is_arrow=True,
        )

        return FileModule(
            file_path=f"{self.config.target_src_dir}/App.tsx",
            language="typescript_react",
            imports=imports,
            top_level=[app_fn],
            header_comment=(
                f"App root - composed from DesignGraph {graph.graph_id}\n"
                f"Variant strategy: {graph.metadata.get('variant_strategy', 'n/a')}\n"
                f"Theme: {graph.theme_profile}"
            ),
        )

    def _build_data_hook_statements(self, graph: DesignGraph) -> List[str]:
        stmts: List[str] = []
        for ds_id, ds in graph.data_sources.items():
            var_name = to_camel_case(ds_id)
            if ds.kind == DataSourceKind.REST:
                url = ds.config.get("url", "/api/unknown")
                stmts.append(
                    f'const {{ data: {var_name}, error: {var_name}Error, '
                    f'isLoading: {var_name}Loading }} = useSWR<{ds.shape_hint}>('
                    f'"{url}", (u) => fetch(u).then(r => r.json()));'
                )
            elif ds.kind == DataSourceKind.STATIC:
                raw = ds.config.get("value")
                stmts.append(
                    f"const {var_name}: {ds.shape_hint} = "
                    f"{json.dumps(raw, ensure_ascii=False)};"
                )
            elif ds.kind == DataSourceKind.STATE:
                initial = ds.config.get("initial", "undefined")
                initial_str = (
                    f'"{initial}"' if isinstance(initial, str) and initial != "undefined"
                    else json.dumps(initial) if not isinstance(initial, str)
                    else initial
                )
                stmts.append(
                    f"const [{var_name}, set{to_pascal_case(ds_id)}] = "
                    f"React.useState<{ds.shape_hint}>({initial_str});"
                )
            elif ds.kind == DataSourceKind.ROUTE_PARAM:
                stmts.append(
                    f"// TODO route param: {var_name} (add react-router / next/router)"
                )
            # graphql / context: TODO cho Phase 5+
        return stmts

    # ============================================================
    # 5. NODE → JSX (recursive)
    # ============================================================

    def _node_to_jsx(
        self,
        node: DesignNode,
        graph: DesignGraph,
        depth: int = 0,
    ) -> JSXNode:
        # Safety: tránh đệ quy quá sâu
        if depth > 20:
            return JSXNode.comment(f"Max depth exceeded at {node.node_id}")

        is_html = self._is_html_tag(node.component_id)
        tag = node.component_id if is_html else to_pascal_case(node.component_id)

        attrs = self._build_node_attributes(node)

        # Build children từ slots
        children_nodes: List[JSXNode] = []
        # Preserve slot order: default first, sau đó các slot khác
        slot_order = ["default"] + [s for s in node.children_by_slot.keys() if s != "default"]
        for slot_name in slot_order:
            child_ids = node.children_by_slot.get(slot_name, [])
            for child_id in child_ids:
                child_node = graph.nodes.get(child_id)
                if child_node is None:
                    continue
                child_jsx = self._node_to_jsx(child_node, graph, depth + 1)
                children_nodes.append(child_jsx)

        # Nếu node là placeholder, thêm comment TODO
        if node.component_id.startswith("placeholder."):
            children_nodes.insert(
                0,
                JSXNode.comment(
                    f"placeholder {node.metadata.get('feature_id', 'unknown')} - "
                    f"needs_llm_fill={node.metadata.get('needs_llm_fill', False)}"
                ),
            )

        return JSXNode.element(
            tag=tag,
            attributes=attrs,
            children=children_nodes,
            self_closing=False,
        )

    def _build_node_attributes(self, node: DesignNode) -> List[JSXAttribute]:
        attrs: List[JSXAttribute] = []

        # 1. key prop (React best practice)
        attrs.append(JSXAttribute("key", node.node_id))

        # 2. Static props
        for prop_name, prop_value in node.props.items():
            if prop_name == "children":
                continue   # handled via slots
            rendered, is_expr = to_jsx_value(prop_value)
            attrs.append(JSXAttribute(
                name=prop_name, value=rendered, is_expression=is_expr,
            ))

        # 3. Data bindings → expression
        for prop_name, source_id in node.data_bindings.items():
            var_name = to_camel_case(source_id)
            attrs.append(JSXAttribute(
                name=prop_name, value=var_name, is_expression=True,
            ))

        # 4. Event handlers
        for event_name, handler_expr in node.event_handlers.items():
            attrs.append(JSXAttribute(
                name=event_name, value=handler_expr, is_expression=True,
            ))

        # 5. className: compose responsive overrides
        class_list = self._compose_classes_for_node(node)
        if class_list:
            attrs.append(JSXAttribute("className", class_list))

        return attrs

    def _compose_classes_for_node(self, node: DesignNode) -> str:
        """Tổng hợp class từ responsive_overrides.className của node."""
        cl = ClassList()

        # Base from props.className nếu có
        base = node.props.get("className")
        if isinstance(base, str):
            cl.add(base)

        # Responsive: bp.className → "sm:foo md:bar"
        for bp_str, overrides in node.responsive_overrides.items():
            if not isinstance(overrides, dict):
                continue
            bp_cls = overrides.get("className")
            if isinstance(bp_cls, str):
                for token in bp_cls.split():
                    cl.add(f"{bp_str}:{token}")

        return cl.render()

    # ============================================================
    # 6. ENTRY POINT (main.tsx)
    # ============================================================

    def _build_main_file(self) -> FileModule:
        strict_wrap = self.config.strict_mode

        body: List[str] = [
            "const container = document.getElementById(\"root\");",
            "if (!container) throw new Error(\"Root element #root not found\");",
            "const root = ReactDOM.createRoot(container);",
        ]
        if strict_wrap:
            body.append("root.render(<React.StrictMode><App /></React.StrictMode>);")
        else:
            body.append("root.render(<App />);")

        fn = FunctionDeclaration(
            name="__apex_factory_bootstrap",
            params=[],
            return_type=TS_VOID,
            body_statements=body,
            exported=False,
            is_default_export=False,
        )
        bootstrap_call = ConstDeclaration(
            name="_boot",
            value_expr="__apex_factory_bootstrap()",
            exported=False,
        )

        return FileModule(
            file_path=f"{self.config.target_src_dir}/main.tsx",
            language="typescript_react",
            imports=[
                ImportSpec(module="react", default_name="React"),
                ImportSpec(module="react-dom/client", namespace_name="ReactDOM"),
                ImportSpec(module="./App", default_name="App"),
            ],
            top_level=[fn, bootstrap_call],
            header_comment="React bootstrap (entry point)",
        )

    # ============================================================
    # 7. SCAFFOLD FILES (renderers)
    # ============================================================

    def _render_postcss_config(self) -> str:
        return (
            "// Auto-generated by APEX FACTORY v6.0\n"
            "module.exports = {\n"
            "  plugins: {\n"
            "    tailwindcss: {},\n"
            "    autoprefixer: {},\n"
            "  },\n"
            "};\n"
        )

    def _render_tailwind_entry_css(self) -> str:
        return (
            "/* Tailwind directives */\n"
            "@tailwind base;\n"
            "@tailwind components;\n"
            "@tailwind utilities;\n"
        )

    def _render_vite_config(self) -> str:
        return (
            "import { defineConfig } from 'vite';\n"
            "import react from '@vitejs/plugin-react';\n"
            "\n"
            "// APEX FACTORY v6.0 - vite.config.ts\n"
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "  server: { port: 5173, host: '0.0.0.0' },\n"
            "  build: { sourcemap: true, target: 'es2020' },\n"
            "});\n"
        )

    def _render_tsconfig(self) -> str:
        content = {
            "compilerOptions": {
                "target": "ES2020",
                "useDefineForClassFields": True,
                "lib": ["ES2020", "DOM", "DOM.Iterable"],
                "module": "ESNext",
                "skipLibCheck": True,
                "moduleResolution": "bundler",
                "allowImportingTsExtensions": False,
                "resolveJsonModule": True,
                "isolatedModules": True,
                "noEmit": True,
                "jsx": "react-jsx",
                "strict": True,
                "noUnusedLocals": True,
                "noUnusedParameters": True,
                "noFallthroughCasesInSwitch": True,
                "esModuleInterop": True,
                "forceConsistentCasingInFileNames": True,
            },
            "include": [self.config.target_src_dir],
            "references": [],
        }
        return json.dumps(content, indent=2) + "\n"

    def _render_package_json(self) -> str:
        dependencies: Dict[str, str] = {
            "react": REACT_VERSION,
            "react-dom": REACT_VERSION,
        }
        if self.config.include_swr:
            dependencies["swr"] = SWR_VERSION

        dev_dependencies: Dict[str, str] = {
            "@types/react": REACT_VERSION,
            "@types/react-dom": REACT_VERSION,
            "@vitejs/plugin-react": "^4.2.1",
            "autoprefixer": AUTOPREFIXER_VERSION,
            "postcss": POSTCSS_VERSION,
            "tailwindcss": TAILWIND_VERSION,
            "typescript": TYPESCRIPT_VERSION,
            "vite": VITE_VERSION,
        }
        pkg = {
            "name": self.config.app_name,
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "description": self.config.description,
            "scripts": {
                "dev": "vite",
                "build": "tsc --noEmit && vite build",
                "preview": "vite preview",
                "typecheck": "tsc --noEmit",
            },
            "dependencies": dependencies,
            "devDependencies": dev_dependencies,
            "engines": {"node": ">=18.0.0"},
        }
        return json.dumps(pkg, indent=2, ensure_ascii=False) + "\n"

    def _render_index_html(self) -> str:
        return (
            "<!DOCTYPE html>\n"
            '<html lang="vi">\n'
            "<head>\n"
            '  <meta charset="UTF-8" />\n'
            '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"  <title>{self.config.app_title}</title>\n"
            f'  <meta name="description" content="{self.config.description}" />\n'
            f'  <meta name="generator" content="APEX FACTORY v6.0" />\n'
            "</head>\n"
            "<body>\n"
            '  <div id="root"></div>\n'
            f'  <script type="module" src="/{self.config.target_src_dir}/main.tsx"></script>\n'
            "</body>\n"
            "</html>\n"
        )

    def _render_gitignore(self) -> str:
        return (
            "# APEX FACTORY v6.0\n"
            "node_modules/\n"
            "dist/\n"
            ".DS_Store\n"
            "*.log\n"
            ".env*\n"
            "!.env.example\n"
            ".vite/\n"
            "coverage/\n"
        )

    def _render_readme(self) -> str:
        return (
            f"# {self.config.app_title}\n\n"
            f"{self.config.description}\n\n"
            "Auto-generated by **APEX FACTORY v6.0**.\n\n"
            "## Chạy dev server\n\n"
            "```bash\n"
            "npm install\n"
            "npm run dev\n"
            "```\n\n"
            "## Build production\n\n"
            "```bash\n"
            "npm run build\n"
            "```\n\n"
            "## Ghi chú\n\n"
            "- Các file có component_id bắt đầu bằng `placeholder.` là STUB - "
            "cần fill bởi B6 Commander (LLM borrowing) hoặc tự viết.\n"
            "- Tailwind config được sinh từ TokenRegistry - không sửa thủ công; "
            "sửa token → emit lại.\n"
        )


# ============================================================
# 8. SANITY CHECK
# ============================================================

def react_emitter_sanity_check() -> Dict[str, bool]:
    from apex_core.foundation.ontology_ui import (
        A11yContract,
        A11yRole,
        ColorToken,
        ComponentCategory,
        ComponentSpec,
        ComponentState,
        PropSchema,
        SlotSchema,
        TokenRole,
    )
    from apex_core.foundation.ui_ir import DesignGraph, DesignNode

    checks: Dict[str, bool] = {}

    # Build catalog
    cat = ComponentCatalog()
    cat.register(ComponentSpec(
        component_id="organism.navbar.default",
        label="Navbar",
        category=ComponentCategory.ORGANISM,
        prop_schema=(PropSchema("brand", "string", required=True),),
        slots=(SlotSchema(name="default"),),
        states=(ComponentState.DEFAULT,),
        a11y=A11yContract(role=A11yRole.NAVIGATION),
        design_tokens_used=(),
        dependencies=(),
        render_targets=(RenderTarget.REACT,),
    ))
    cat.register(ComponentSpec(
        component_id="atom.button.primary",
        label="Primary Button",
        category=ComponentCategory.ATOM,
        prop_schema=(
            PropSchema("label", "string", required=True),
            PropSchema("onClick", "any"),
        ),
        slots=(),
        states=(ComponentState.DEFAULT, ComponentState.HOVER),
        a11y=A11yContract(
            role=A11yRole.BUTTON,
            keyboard_map=(("Enter", "activate"),),
        ),
        design_tokens_used=("brand.primary.600",),
        dependencies=(),
        render_targets=(RenderTarget.REACT,),
    ))

    # Registry
    reg = TokenRegistry()
    reg.add(ColorToken(
        token_id="brand.primary.600",
        value="#2563EB",
        role=TokenRole.PRIMARY,
    ))
    reg.freeze()

    # Graph
    g = DesignGraph(graph_id="g_demo", target=RenderTarget.REACT, root_id="root")
    g.add_node(DesignNode(node_id="root", component_id="div"))
    g.add_node(DesignNode(
        node_id="nav", component_id="organism.navbar.default",
        props={"brand": "Acme"},
    ))
    g.add_node(DesignNode(
        node_id="cta", component_id="atom.button.primary",
        props={"label": "Sign up"},
        event_handlers={"onClick": "() => alert('hi')"},
    ))
    g.link("root", "default", "nav")
    g.link("root", "default", "cta")

    emitter = ReactEmitter(cat, reg)
    result = emitter.emit_graph(g)

    checks["emit_returns_result"] = isinstance(result, EmitResult)
    checks["has_app_file"] = any(f.file_path.endswith("App.tsx") for f in result.files)
    checks["has_main_file"] = any(f.file_path.endswith("main.tsx") for f in result.files)
    checks["has_navbar_file"] = any(
        "OrganismNavbarDefault" in f.file_path for f in result.files
    )
    checks["has_button_file"] = any(
        "AtomButtonPrimary" in f.file_path for f in result.files
    )
    checks["has_package_json"] = "package.json" in result.scaffold_files
    checks["has_tailwind_config"] = "tailwind.config.js" in result.scaffold_files
    checks["has_tokens_css"] = any(
        "tokens.css" in p for p in result.scaffold_files.keys()
    )
    checks["has_vite_config"] = "vite.config.ts" in result.scaffold_files

    # Render App.tsx check
    app_file = next(f for f in result.files if f.file_path.endswith("App.tsx"))
    rendered = app_file.render()
    checks["app_imports_navbar"] = "OrganismNavbarDefault" in rendered
    checks["app_imports_button"] = "AtomButtonPrimary" in rendered
    checks["app_has_jsx_root"] = "<div" in rendered and "</div>" in rendered
    checks["app_passes_brand_prop"] = 'brand="Acme"' in rendered
    checks["app_on_click_expr"] = "onClick={() =>" in rendered

    # Component file render check
    btn_file = next(
        f for f in result.files if "AtomButtonPrimary" in f.file_path
    )
    btn_rendered = btn_file.render()
    checks["btn_has_props_interface"] = "interface AtomButtonPrimaryProps" in btn_rendered
    checks["btn_label_required"] = "label: string;" in btn_rendered
    checks["btn_role_button"] = 'role="button"' in btn_rendered

    # Package.json check
    pkg = json.loads(result.scaffold_files["package.json"])
    checks["pkg_has_react"] = "react" in pkg["dependencies"]
    checks["pkg_has_tailwind"] = "tailwindcss" in pkg["devDependencies"]
    checks["pkg_scripts_ok"] = {"dev", "build"} <= set(pkg["scripts"].keys())

    return checks


__all__ = [
    "REACT_EMITTER_VERSION",
    "REACT_VERSION", "TYPESCRIPT_VERSION", "VITE_VERSION", "TAILWIND_VERSION",
    "HTML_TAGS",
    "EmitConfig", "EmitResult",
    "ReactEmitter",
    "react_emitter_sanity_check",
]
